name: PHP-CS-Fixer

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    name: PER

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug
          tools: cs2pr
      - run: composer install --prefer-dist --no-interaction
      - run: vendor/bin/php-cs-fixer fix --dry-run --format=checkstyle | cs2pr
