name: PHP-CS-Fixer

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    name: PER-CS

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug
          tools: php-cs-fixer, cs2pr
      - run: php-cs-fixer fix . --dry-run --rules=@PER-CS,declare_strict_types,no_unused_imports,ordered_imports,ordered_traits --allow-risky=yes --format=checkstyle | cs2pr
